[package]
name = "super_template"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["FishyySquishyy"]
license = "MIT"
description = "A template for FishyySquishyy"
compiler = "0.11.1"
exclude = ["*.pdf"]
